-- Миграция: связь бронь → конкретное Google-событие.
-- Шаг A для задачи 3b-2 (двусторонний жизненный цикл брони в Google).
--
-- Сейчас createBookingEvent (src/integrations.js) возвращает eventId и
-- calendarId, но они нигде не сохраняются. Без этой связи невозможно
-- удалить или обновить событие в Google, когда коуч отменит/перенесёт
-- бронь в kogDA — Google продолжит показывать слот занятым через FreeBusy.
--
-- Две колонки в bookings:
--  1) google_event_id  — id события в Google Calendar API.
--  2) google_calendar_id — id календаря, в котором это событие лежит.
--
-- Почему дублируем google_calendar_id здесь (он уже есть в
-- calendar_connections):
--  а) при отмене брони не нужен лишний JOIN к calendar_connections —
--     всё что нужно для DELETE Google-события лежит прямо в bookings;
--  б) если коуч отключит и заново подключит Google к новому аккаунту,
--     calendar_connections.google_calendar_id сменится на новый, но
--     старые брони останутся привязаны к своему историческому
--     календарю/событию (даже если оно уже недоступно — мы хотя бы
--     знаем, что пытаться удалять там не надо).
--
-- Обе колонки nullable: брони, созданные ДО этой миграции, и брони
-- коучей без подключённого Google останутся с NULL — это нормально,
-- значит "Google-события для этой брони нет".
--
-- Заполняется кодом (на следующем шаге 3b-2), не миграцией.
-- Идемпотентно — миграции применяются при каждом старте.

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS google_event_id TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS google_calendar_id TEXT;
